### ISSUE TITLE
Bug: 제출물을 요구하지 않는 과제에서 일자 표기 관련 오류

### ISSUE THREAD

**Issue by dotjm** [kangju2000/gachon-tools#2]
**버그 설명**
제출물을 요구하지 않는 어떤 상호작용도 없는 과제 (상세 페이지에 "과제에서 온라인 제출물을 요구하지 않습니다."와 같이 적혀있는 겨우)가 발견될 경우. 기한 정보가 undefined로 표기되고, D-Day는 NaN으로 표기되는 오류

**재현 방법**

1. 확장앱의 업데이트 기능을 이용하여 정보 불러옴
2. 과제로 분류된 것 중 제출할 과제물이 없는 과제물의 정보를 확인
3. 기한 정보가 모두 undefined, D-Day가 D-NaN으로 표기된 것을 확인

**발생되는 오류**
기한 정보가 undefined로 표기되고, D-Day는 NaN으로 표기되는 오류발생

**스크린샷**
![Screenshot 2023-05-23 at 01 29 36 Marking](https://github.com/kangju2000/gachon-extension/assets/46292908/391db885-dce4-4263-a5d5-119050fa3513)

**PC 정보**

- OS : Windows 11 Home
- Browser : Whale 3.20.182.14(공식 빌드) (64비트) 
- Version : 22H2 (22621.1702)

**추가 설명**
없음.

**Comment by kangju2000** [comment]
현재 웨일 확장프로그램이 v1.0.6.1 -> v1.0.7.5 로 업데이트 심사 중에 있습니다! 업데이트가 완료되는대로 위와 같은 에러가 발생하는지 확인하시고 코멘트 남겨주시면 감사하겠습니다 :)

[크롬 웹스토어](https://chrome.google.com/webstore/detail/gachon-tools-%EC%82%AC%EC%9D%B4%EB%B2%84%EC%BA%A0%ED%8D%BC%EC%8A%A4-%ED%99%95%EC%9E%A5%ED%94%84%EB%A1%9C%EA%B7%B8/ogldncimhepjdfadhjjhkchknloncnmg?hl=ko&authuser=0)에서 v1.0.7.5로 배포 중이니, 바로 변경 사항을 확인하실 수 있습니다.

**Comment by dotjm** [comment]
웨일 확장 스토어 기준 최신버전 v1.0.7.4 기준 동일 오류 발생됩니다! 
또 웨일에서 삭제 후, 크롬 스토어에서 v1.0.7.5 설치해도 오류 발생됩니다!

**Comment by kangju2000** [comment]
다음과 같이 체크해주신다면 원인 분석에 도움이 될 것 같습니다!
어드민 계정이 없어 예외 상황에 대한 처리가 부족한 상황입니다.. 도움 주시면 감사하겠습니다 :)

## 일반 과제

- 강의 페이지에서 해당 과제가 어떻게 보이는지   
https://cyber.gachon.ac.kr/course/view.php?id={강의id}
<img width="497" alt="image" src="https://github.com/kangju2000/gachon-extension/assets/23312485/6bc9132d-c489-4d65-adce-b072886f8b35">


- 강의의 학습활동 -> 과제 페이지에서 해당 과제가 어떻게 보이는지
https://cyber.gachon.ac.kr/mod/assign/index.php?id={강의id}

<img width="1017" alt="image" src="https://github.com/kangju2000/gachon-extension/assets/23312485/37c433c8-4a70-4ecb-8211-bdd6063112e8">


## 동영상 과제

- 강의 페이지에서 해당 동영상 과제가 어떻게 보이는지   
https://cyber.gachon.ac.kr/course/view.php?id={강의id}
<img width="482" alt="image" src="https://github.com/kangju2000/gachon-extension/assets/23312485/c017be7c-6c6e-42cb-941b-28ddd32d4495">


- 강의의 성적/출석관리 -> 학습진도현황 or 온라인 출석부 페이지에서 해당 동영상 과제가 어떻게 보이는지
https://cyber.gachon.ac.kr/report/ubcompletion/progress.php?id={강의id}
<img width="946" alt="image" src="https://github.com/kangju2000/gachon-extension/assets/23312485/4e14adf3-6ee5-4402-892f-b717881839f6">

**Comment by kangju2000** [comment]
2버전으로 업데이트하면서 UI가 바뀌었습니다. 이에 따라 해당 이슈가 해결되었다고 판단하여 이슈를 닫습니다.
