### ISSUE TITLE
[Bug]: 아이콘 종료시 안켜짐

### ISSUE THREAD

**Issue by SalkCoding** [kangju2000/gachon-tools#88]
### 어떤 문제가 발생했나요?

Opera 113.0.5230.86 버전 사용중입니다.

처음에 총장님의 얼굴로 아이콘이 바뀌였었는데
설정 눌러서 들어갔더니 종료되고, 이후로는 아예 작동하지 않습니다.

단축키도 눌러보고 브라우저도 재시작 해봤는데 아예 먹통입니다.

감사합니다.

### 현재 사용하는 익스텐션 버전

2.0.1

### 어떤 브라우저에서 문제가 발생했나요?

Chrome

**Comment by kangju2000** [comment]
안녕하세요 @SalkCoding 님!

해당 이슈 재현이 어려워서 아래 절차를 통해 스크린샷을 올려주시면 감사하겠습니다! 🙇‍♂️


1. 사이버 캠퍼스에서 `마우스 우측 버튼` 클릭
2. `요소 검사` 클릭
3. `Console 탭` 클릭
4. 해당 탭에서 나오고 있는 콘솔 캡쳐

**Comment by SalkCoding** [comment]
![image](https://github.com/user-attachments/assets/5731260e-34cf-4e2c-aa37-6d168723bb24)

재부팅 후에 찍었습니다!

**Comment by kangju2000** [comment]
@SalkCoding 
2.0.2 버전으로 릴리즈했습니다!

업데이트가 안된다면, [수동 업데이트 가이드](https://kangju2000.notion.site/ff90da1ba0324066bd85481b029ebc24)를 참고해주시기 바랍니다.

만약 해당 이슈가 계속 재현된다면 재문의 부탁드립니다. 🙇‍♂️

**Comment by SalkCoding** [comment]
@kangju2000 

이슈 해결되었습니다. 
감사합니다!
